### ISSUE TITLE
CiviMonitor on Civi 4.7

### ISSUE THREAD

**Issue by MegaphoneJon** [aghstrategies/com.aghstrategies.civimonitor#7]
We're running Civi 4.7 beta with CiviMonitor, and I thought it was time to start the conversation of "where to from here?".  There's a few questions to answer.

Given the work we've done on Civi 4.7, I'm not even sure if CiviMonitor needs to exist as an extension anymore.  I haven't used the payment processor check, so I'm not 100% sure what that does - but I suspect that it can be added to the status page with hook_check instead of defining a separate API.

There's also the matter of check_civicrm.php.  I think that we can probably eliminate all the checks except "system" now, right?  I think that was one of our design goals, so hopefully that's the case.  This should make my Nagios admin coworker happy!

Finally, and perhaps most important - the API call System.check in 4.7 returns ALL statuses.  I believe this is the change we discussed right before this code was merged.  This means that the system check in check_civicrm.php will always return an issue.

I think we need to update check_civicrm.php to expect JSON on system check, and it should know how to ignore messages below a certain severity.  Does this sound right to you?  It's not much work, I can probably have someone do it, but I wanted to confirm plans with you first.

**Comment by agh1** [comment]
Yeah, I've done a bit of idle thinking but no actual work on this.  I agree that this extension probably doesn't need to exist.  Payment processor check is mainly a way for us to have a bird's-eye view on who's using what--I wrote it when we needed to track down everyone using Authorize.net when their certificate stopped being trusted by Ubuntu.

Anyway, things like that are really new checks to add to system check, so I agree that the only thing Nagios should be checking is the system check.

Yes, by default, system.check returns everything with a message, regardless of whether it's hushed or snoozed.  You can send is_visible=1 to filter out the hushed and snoozed messages--that's what drives the actual status page.

However, I wonder if from a monitoring perspective we should be ignoring the hush/snooze because a site admin might decide to hush something that they think is annoying but we think is important.  Instead, Nagios should decide that any severity_id >= 4 is a warning and any severity_id >= 5 is a critical (or whatever thresholds make sense).

**Comment by MegaphoneJon** [comment]
I propose that check_civicrm.php can be passed arguments for "only show severity of X and up" and "show only visible messages", but with sensible defaults for each?

I considered whether the permissioning in CiviMonitor (bgm's work) merited keeping an extension around - but I did some reading on CiviConnect, which allows permissioning on specific API actions, and it looks like it's dropping in 4.6.11/4.7, so I guess we wait and see?

**Comment by agh1** [comment]
I actually think that over time, check_civicrm.php is actually going to be a fairly specific to whoever's doing the monitoring and/or the sites being monitored.  In other words, you might always install coop.palantetech.jonsawesomechecks which adds checks for things you care about, and you'd want check_civicrm.php to pay attention to those.  Meanwhile, a client of yours might install com.hacksamillion.crapchecks which generates a bunch of messages (critical or otherwise) you want to ignore.  To deal with this, check_civicrm might have an explicit array of checks to pay attention to, including the ones that ship with 4.7, and you might modify your local copy on your Nagios server to add others.

Good thought about the permissioning.  I guess there are three options:
1. Keep that part of the extension, allowing Access AJAX API + Access CiviMonitor to be sufficient for a monitoring user,
2. Add a Access System Check API permission to core, being basically the same thing as Access CiviMonitor here, or
3. Wait for CiviConnect.

Obviously, 1 and 2 could work alongside 3.  My understanding of CiviConnect was that it was going to be only for a limited library of free services, exclusively available to CiviCRM members.  Tim and I had talked at the Colorado sprint about offering our "basic monitoring" plan as a free member perk through this, and momentum on CiviConnect seems to have ebbed and flowed (we were told it would start this fall, but then there hasn't been as much activity).

Consequently, I think it would be worthwhile to go with option 1 or 2 so that you and I, for example, could continue to support our clients who can't/won't become members, and for continuity as people upgrade to 4.7.  I opened an issue on Jira (https://issues.civicrm.org/jira/browse/CRM-17756) proposing adding it to core, just so there's a venue for people to comment.

**Comment by MegaphoneJon** [comment]
Hi Andrew,

I was going to work on updating check_civicrm.php this week, then noticed CRM-17820, which suggests you're doing the same.  I just didn't want to duplicate work here if you've already begun!

My plan was to basically change the arguments from something like:

```
check_civicrm.php $HOSTADDRESS$ $_HOSTHTTP$ $_HOSTCMS$ $_HOSTSITE_KEY$ $_HOSTAPI_KEY $SERVICE
```

to:

```
check_civicrm.php $HOSTADDRESS$ $_HOSTHTTP$ $_HOSTCMS$ $_HOSTSITE_KEY$ $_HOSTAPI_KEY $WARNING_THRESHOLD $CRITICAL_THRESHOLD $IS_VISIBLE
```

...with appropriate defaults for the new options, of course.

Internally, we'd probably end up ripping out all the service-specific code and writing new code.  Let me know if you'd like me to take a first crack, or if it's already underway!

**Comment by MegaphoneJon** [comment]
Hi Andrew,

I just wrote a check_civicrm.php check that's compatible with Civi 4.7 here: https://github.com/PalanteJon/check_civicrm

I removed the check type - there's only one check now - and added parameters to ignore/show hushed messages, and to set a custom mapping for Civi severity IDs to Nagios warning/critical.  Give it a shot if you're inclined!
